api:

  common:
    version: 1.0.0
    title: Account services API
    description: Description of the API...
    termsOfServiceUrl: MINE TERMS OF SERVICE URL
    license: License
    licenseUrl: MY LICENSE URL

    contact:
      name: Contact
      url: My
      email: me@mail.com

  account:

    get-account:
      description: Returns a details view of the specified account id
      notes: |
        # Normal response
        If the requested account id is found the method will return information regarding:
        1. Base account information
        1. Service Addresses\n(technical information regarding the addresses of the microservices that created the response)

        # Expected partial and error responses
        In the following cases, only a partial response be created (used to simplify testing of error conditions)

        ## id 113
        200 - Ok, but no transactions will be returned

        ## Product id 213
        200 - Ok, but no categories will be returned

        ## Non numerical  id
        400 - A <b>Bad Request</b> error will be returned

        ## id 13
        404 - A <b>Not Found</b> error will be returned

        ## Negative ids
        422 - An <b>Unprocessable Entity</b> error will be returned




server.port: 7001
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: account-db


logging:
level:
  root: INFO
  com.marvin: DEBUG
  org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.profiles: docker

server.port: 8080

spring.data.mongodb.host: mongodb